DROP TABLE IF EXISTS dic_exam_results CASCADE;
DROP TABLE IF EXISTS dic_assignment_submissions CASCADE;
DROP TABLE IF EXISTS dic_assignments CASCADE;
DROP TABLE IF EXISTS dic_exams CASCADE;
DROP TABLE IF EXISTS dic_applications CASCADE;
DROP TABLE IF EXISTS dic_course_videos CASCADE;
DROP TABLE IF EXISTS dic_courses_enrollments CASCADE;
DROP TABLE IF EXISTS dic_students CASCADE;
DROP TABLE IF EXISTS dic_programs_courses CASCADE;
DROP TABLE IF EXISTS dic_courses CASCADE;
DROP TABLE IF EXISTS dic_staffs CASCADE;
DROP TABLE IF EXISTS dic_programs CASCADE;
DROP TABLE IF EXISTS dic_departments CASCADE;
DROP TABLE IF EXISTS dic_degrees CASCADE;
DROP TABLE IF EXISTS dic_batches CASCADE;
DROP TABLE IF EXISTS dic_accounts CASCADE;
DROP TABLE IF EXISTS dic_account_types CASCADE;

DROP EXTENSION IF EXISTS pgcrypto CASCADE;

