DROP TABLE IF EXISTS dic_applications CASCADE;
DROP TABLE IF EXISTS dic_courses CASCADE;
DROP TABLE IF EXISTS dic_programs CASCADE;
DROP TABLE IF EXISTS dic_departments CASCADE;
DROP TABLE IF EXISTS dic_accounts CASCADE;
DROP TABLE IF EXISTS dic_account_types CASCADE;

